<script setup lang="ts">
import { reactive, watch } from "vue";
import { useRouter } from "vue-router";
import { usePlatformStore } from "../stores/platform";
const store = usePlatformStore(); const router = useRouter();
const draft = reactive({ runtime_url: "", api_base_url: "", sandbox_command: "", sandbox_image: "" });
watch(() => store.project, value => Object.assign(draft, { runtime_url: value?.runtime_url ?? "", api_base_url: value?.api_base_url ?? "", sandbox_command: value?.sandbox_command ?? "", sandbox_image: value?.sandbox_image ?? "" }), { immediate: true });
const names = ["sca", "sast", "agent", "dast", "sandbox"];
</script>
<template>
  <section class="panel full asset-config"><div class="panel-header"><h2>项目资产配置</h2><span>{{ store.project ? "影响 DAST 与 SANDBOX 默认参数" : "请先选择项目" }}</span></div><div class="asset-config-grid"><label>运行地址<input v-model="draft.runtime_url" placeholder="http://localhost:3000" :disabled="!store.project || store.loading" /></label><label>API 地址<input v-model="draft.api_base_url" placeholder="http://localhost:3000/api" :disabled="!store.project || store.loading" /></label><label>沙箱命令<input v-model="draft.sandbox_command" placeholder="npm test" :disabled="!store.project || store.loading" /></label><label>沙箱镜像<input v-model="draft.sandbox_image" placeholder="node:20-alpine" :disabled="!store.project || store.loading" /></label></div><div class="asset-config-actions"><button class="primary-action" :disabled="!store.project || store.loading" @click="store.updateProject(draft)">保存资产配置</button></div></section>
  <section class="asset-workspace">
    <section class="module-summary"><div class="metric-card"><span>资产路径</span><strong>{{ store.assetProbe ? (store.assetProbe.path_exists ? "路径可访问" : "路径不可访问") : "未探测" }}</strong></div><div class="metric-card"><span>依赖清单</span><strong>{{ store.assetProbe?.sca_files?.length ?? 0 }}</strong></div><div class="metric-card"><span>源码文件</span><strong>{{ store.assetProbe?.source_files?.length ?? 0 }}</strong></div><div class="metric-card"><span>推荐任务</span><strong>{{ store.assetProbe?.recommended_tasks?.length ?? 0 }}</strong></div></section>
    <div class="asset-grid"><div class="panel asset-hero full"><div><div class="panel-header"><h2>{{ store.project?.name ?? "未选择项目" }}</h2><span>{{ store.project?.default_branch ?? "main" }}</span></div><div class="asset-path">{{ store.project?.source_path ?? store.assetProbe?.source_path ?? "未配置本地源码路径" }}</div><div class="asset-tags"><span>{{ store.project?.repository_url ?? "未配置仓库" }}</span><span>业务：{{ store.project?.business_owner ?? "未配置" }}</span><span>安全：{{ store.project?.security_owner ?? "未配置" }}</span></div></div><div class="asset-actions"><button class="primary-action" :disabled="!store.project || !(store.assetProbe?.recommended_tasks?.length)" @click="router.push('/detection')">执行推荐任务</button><button class="secondary-action" @click="router.push('/detection')">配置模块</button></div></div>
      <div class="panel"><div class="panel-header"><h2>识别结果</h2><span>{{ store.assetProbe?.message ?? "暂无探测结果" }}</span></div><div class="output-strip"><div><span>SCA</span><strong>{{ store.assetProbe?.sca_files?.length ?? 0 }}</strong></div><div><span>SAST</span><strong>{{ store.assetProbe?.source_files?.length ?? 0 }}</strong></div><div><span>AGENT</span><strong>{{ store.assetProbe?.agent_files?.length ?? 0 }}</strong></div></div><div class="asset-note">{{ store.assetProbe?.recommended_tasks?.length ? `当前可直接执行：${store.assetProbe.recommended_tasks.filter((i:string) => store.enabled(i as any)).map((i:string) => i.toUpperCase()).join(' + ')}` : "暂无可直接执行的推荐任务" }}</div></div>
      <div class="panel"><div class="panel-header"><h2>模块准备度</h2><span>{{ names.filter(i => store.enabled(i as any)).length }} 个已启用</span></div><div class="readiness-list"><div v-for="name in names" :key="name" class="readiness-row"><span>{{ name.toUpperCase() }}</span><strong :class="store.enabled(name as any) ? 'ready' : 'muted'">{{ store.enabled(name as any) ? "已接入" : "未接入" }}</strong></div></div></div>
      <div class="panel full"><div class="panel-header"><h2>资产文件</h2><span>来自本地源码路径自动识别</span></div><div class="asset-file-grid"><div v-for="[title, files] in [['依赖清单',store.assetProbe?.sca_files ?? []],['源码文件',store.assetProbe?.source_files ?? []],['Agent 配置',store.assetProbe?.agent_files ?? []]]" :key="title as string" class="asset-file-list"><h3>{{ title }}</h3><span v-if="!(files as any[]).length" class="empty-inline">暂无文件</span><ul v-else><li v-for="file in (files as any[]).slice(0,8)" :key="file">{{ file }}</li><li v-if="(files as any[]).length > 8">还有 {{ (files as any[]).length - 8 }} 个文件</li></ul></div></div></div>
      <div class="panel full"><div class="panel-header"><h2>当前项目结果</h2><span>进入 ASPM 治理总览前的资产侧摘要</span></div><div class="output-strip wide"><div><span>组件</span><strong>{{ store.summary?.component_count ?? store.components.length }}</strong></div><div><span>Findings</span><strong>{{ store.summary?.finding_count ?? store.findings.length }}</strong></div><div><span>DAST 验证</span><strong>{{ store.summary?.dast_validation_count ?? store.validations.length }}</strong></div><div><span>Sandbox 证据</span><strong>{{ store.summary?.sandbox_evidence_count ?? store.evidence.length }}</strong></div></div></div>
    </div>
  </section>
</template>
