<script setup lang="ts">
import { Activity, Boxes, Bug, FlaskConical, Network } from "lucide-vue-next";
import { usePlatformStore, type ModuleKey } from "../stores/platform";
const store = usePlatformStore();
const display: Record<string, any> = { sca: ["SCA 供应链风险", "检查第三方组件、已知漏洞和许可证风险", Boxes], sast: ["SAST 代码安全", "检查源代码中的高风险实现和安全缺陷", Bug], agent: ["AGENT 智能体安全", "检查 Agent、MCP、工具和插件配置风险", Network], dast: ["DAST 动态验证", "访问运行中的系统，验证风险是否能够触发", Activity], sandbox: ["SANDBOX 沙箱证据", "隔离运行程序并采集进程、输出和策略证据", FlaskConical] };
const optional = () => store.modules.filter(i => i.key !== "aspm");
const statusLabel: Record<string,string> = { waiting:"等待",running:"执行中",completed:"已完成",failed:"失败",skipped:"已跳过" };
</script>
<template><section class="security-center">
  <div class="panel detection-intro"><div><h2>安全能力接入</h2><p>按项目需要选择模块。ASPM 治理底座始终启用，检测结果会自动进入治理总览。</p></div><div class="detection-selection-count"><strong>{{ optional().filter(i => store.enabled(i.key)).length }}</strong><span>个检测模块已接入</span></div></div>
  <div class="detection-module-grid"><article v-for="module in optional()" :key="module.key" class="detection-module-card" :class="{ enabled: store.enabled(module.key) }"><div class="detection-module-heading"><span class="module-icon"><component :is="display[module.key]?.[2]" :size="20" /></span><div><strong>{{ display[module.key]?.[0] ?? module.name }}</strong><span>{{ display[module.key]?.[1] ?? module.description }}</span></div></div><button class="module-select-button" :class="{ selected: store.enabled(module.key) }" :disabled="!store.project || store.loading" @click="store.toggleModule(module.key as ModuleKey)">{{ store.enabled(module.key) ? "已接入" : "接入模块" }}</button></article></div>
  <section v-if="store.enabled('dast') || store.enabled('sandbox')" class="relation-notices"><h3>模块关系提示</h3><div v-if="store.enabled('dast')" class="relation-notice"><span>{{ store.enabled('sast') || store.enabled('sca') ? "DAST 将在静态或供应链检查之后执行，用于补充动态验证结论。" : "DAST 可以独立探测网站，但接入 SAST 或 SCA 后才能针对已发现风险进行验证。" }}</span><button v-if="!store.enabled('sast') && !store.enabled('sca')" class="secondary-action" @click="store.toggleModule('sast')">同时接入 SAST</button></div><div v-if="store.enabled('sandbox')" class="relation-notice"><span>{{ store.enabled('agent') || store.enabled('dast') ? "SANDBOX 将在其他检测完成后执行，为相关风险补充隔离运行证据。" : "SANDBOX 可以独立运行，但与 AGENT 或 DAST 组合后更容易形成可追溯证据。" }}</span><button v-if="!store.enabled('agent') && !store.enabled('dast')" class="secondary-action" @click="store.toggleModule('agent')">同时接入 AGENT</button></div></section>
  <section class="panel detection-config"><div class="panel-header"><h2>执行配置</h2><span>只显示已接入模块所需的参数</span></div><div v-if="!optional().some(i => store.enabled(i.key))" class="empty-project">请先选择需要接入的安全模块。</div><div v-else class="detection-config-grid"><label v-if="['sca','sast','agent'].some(i => store.enabled(i as any))"><span>项目源码路径</span><input :value="store.sourcePath" placeholder="项目源码所在目录" @input="store.setUnifiedSourcePath(($event.target as HTMLInputElement).value)" /></label><label v-if="store.enabled('dast')"><span>动态验证地址</span><input v-model="store.targetUrl" placeholder="https://项目运行地址" /></label><template v-if="store.enabled('sandbox')"><label><span>沙箱运行命令</span><input v-model="store.runCommand" placeholder="例如：python app.py" /></label><label><span>沙箱镜像</span><input v-model="store.sandboxImage" placeholder="例如：python:3.12-slim" /></label></template></div></section>
  <section class="panel detection-run-panel"><div class="detection-run-copy"><h2>一键执行安全检测</h2><p>系统按照 SCA → SAST → AGENT → DAST → SANDBOX 的顺序执行已接入模块，单个模块失败不会阻断后续检查。</p></div><button class="primary-action run-all-button" :disabled="!store.project || store.unifiedLoading || !optional().some(i => store.enabled(i.key))" @click="store.runUnified">{{ store.unifiedLoading ? "检测执行中" : "一键执行" }}</button><div v-if="store.executionSteps.length" class="execution-progress"><div v-for="step in store.executionSteps" :key="step.module" class="execution-step" :class="step.status"><span>{{ display[step.module]?.[0] }}</span><strong>{{ statusLabel[step.status] }}</strong><small>{{ step.detail }}</small></div></div></section>
</section></template>
