<script setup lang="ts">
import { computed, ref } from "vue";
import { ArrowRight, BookOpen } from "lucide-vue-next";
import { usePlatformStore } from "../stores/platform";
import ScaView from "./ScaView.vue"; import SastView from "./SastView.vue"; import ModuleView from "./ModuleView.vue";
const store = usePlatformStore(); const scope = ref("overview");
const display: Record<string,string> = { sca:"SCA 供应链风险",sast:"SAST 代码安全",agent:"AGENT 智能体安全",dast:"DAST 动态验证",sandbox:"SANDBOX 沙箱证据" };
const scopes = computed(() => ["overview", ...["sca","sast","agent","dast","sandbox"].filter(i => store.enabled(i as any))]);
const closed = new Set(["fixed","closed","false_positive","accepted_risk"]);
const active = computed(() => store.findings.filter(i => !closed.has(i.status)));
const validationIds = computed(() => new Set(store.validations.map(i => i.finding_id).filter(Boolean)));
const evidenceIds = computed(() => { const ids=new Set<string>(); const byId=new Map(store.validations.map(i=>[i.id,i])); store.evidence.forEach(i=>{if(i.finding_id)ids.add(i.finding_id); const findingId=i.validation_id ? byId.get(i.validation_id)?.finding_id : null; if(findingId)ids.add(findingId)}); return ids; });
const lifecycle = computed(() => [["多源发现",store.findings.length,"SAST / SCA / AGENT"],["等待验证",active.value.filter(i=>!validationIds.value.has(i.id)&&!evidenceIds.value.has(i.id)).length,"需要动态证明"],["DAST 验证",active.value.filter(i=>validationIds.value.has(i.id)).length,"业务运行态结论"],["SANDBOX 取证",active.value.filter(i=>evidenceIds.value.has(i.id)).length,"隔离运行证据"],["整改 / 复测",store.findings.filter(i=>i.status==='fixing'||i.status==='retest').length,"修复进行中"],["已闭环",store.findings.filter(i=>i.status==='fixed'||i.status==='closed').length,"修复后未再发现"]]);
const priority = computed(() => [...active.value].sort((a,b)=>(evidenceIds.value.has(b.id)?2:validationIds.value.has(b.id)?1:0)-(evidenceIds.value.has(a.id)?2:validationIds.value.has(a.id)?1:0)).slice(0,3));
const severityLabel=(v:any)=>({critical:"严重",high:"高危",medium:"中危",low:"低危",info:"提示"}[v as string]??v??"未知");
const statusLabel=(v:any)=>({open:"待处理",pending:"待处理",confirmed:"已确认",fixing:"整改中",retest:"待复测",fixed:"已修复",closed:"已关闭",false_positive:"误报",accepted_risk:"接受风险"}[v as string]??v??"待处理");
const workflow=["open","confirmed","fixing","retest","fixed","closed","false_positive","accepted_risk"];
function linked(f:any){const validations=store.validations.filter(i=>i.finding_id===f.id||(f.component_id&&i.component_id===f.component_id));const ids=new Set(validations.map(i=>i.id));const evidence=store.evidence.filter(i=>i.finding_id===f.id||(f.component_id&&i.component_id===f.component_id)||(i.validation_id&&ids.has(i.validation_id)));return{validations,evidence}}
</script>
<template><div v-if="!store.project" class="panel empty-project">请先选择项目，再查看治理结果。</div><section v-else class="governance-center">
  <nav class="governance-scope" aria-label="治理查看范围"><button v-for="item in scopes" :key="item" :class="{active:scope===item}" @click="scope=item">{{ item === 'overview' ? '综合总览' : display[item] }}</button></nav>
  <div v-if="scope==='overview'" class="governance-view governance-closed-loop">
    <section class="governance-hero panel"><div><span class="section-kicker">ASPM 项目安全治理</span><h2>从发现风险到动态证明，再到整改复测</h2><p>总览不只是汇总结果，而是回答每个问题现在走到了哪一步、证据是否充分、下一步由谁处理。</p></div><div class="governance-score"><span>项目风险分</span><strong>{{ store.summary?.risk_score ?? 0 }}</strong><small>分数越高，当前风险越集中</small></div></section>
    <section class="security-lifecycle panel"><div class="panel-header"><h2>风险处理流程</h2><span>点击上方模块页可查看各阶段完整结果</span></div><div class="lifecycle-track"><template v-for="(stage,index) in lifecycle" :key="stage[0]"><div class="lifecycle-stage"><span>{{ index+1 }}</span><strong>{{ stage[1] }}</strong><b>{{ stage[0] }}</b><small>{{ stage[2] }}</small></div><ArrowRight v-if="index<lifecycle.length-1" class="lifecycle-arrow" :size="18" /></template></div></section>
    <section class="panel evidence-chain-panel"><div class="panel-header"><div><h2>漏洞证据闭环</h2><span>静态发现 → 动态验证 → 运行时取证 → 整改复测</span></div><strong>{{ new Set([...validationIds,...evidenceIds]).size }} 条风险已有动态证据</strong></div><div v-if="!priority.length" class="empty-project">当前没有待治理风险。重新执行模块后，新发现会进入这里。</div><div v-else class="risk-chain-list"><article v-for="finding in priority" :key="finding.id" class="risk-chain-card"><div class="risk-chain-heading"><div><span class="severity" :class="finding.severity">{{ severityLabel(finding.severity) }}</span><strong>{{ finding.title }}</strong><small>{{ finding.source }} · {{ finding.file_path ?? '项目级风险' }}</small></div><div><span class="chain-conclusion" :class="linked(finding).evidence.length?'proven':linked(finding).validations.length?'validated':'waiting'">{{ linked(finding).evidence.length?'已有运行时证据':linked(finding).validations.length?'已完成动态验证':'等待动态验证' }}</span><select :value="finding.status" @change="store.updateFinding(finding.id,{status:($event.target as HTMLSelectElement).value})"><option v-for="item in workflow" :key="item" :value="item">{{ statusLabel(item) }}</option></select></div></div><div class="chain-timeline"><div class="chain-step done"><span>{{ finding.source }}</span><strong>发现风险</strong><small>{{ finding.evidence ?? finding.rule_id }}</small></div><ArrowRight :size="16"/><div class="chain-step" :class="linked(finding).validations.length?'done':'waiting'"><span>DAST</span><strong>{{ linked(finding).validations.length ? linked(finding).validations[0].verdict : '等待验证' }}</strong><small>{{ linked(finding).validations[0]?.evidence_summary ?? '需要在运行系统中确认是否可触发' }}</small></div><ArrowRight :size="16"/><div class="chain-step" :class="linked(finding).evidence.length?'done':'waiting'"><span>SANDBOX</span><strong>{{ linked(finding).evidence.length?'已取得运行证据':'等待取证' }}</strong><small>{{ linked(finding).evidence[0]?.evidence_summary ?? '必要时在隔离环境中观察行为' }}</small></div><ArrowRight :size="16"/><div class="chain-step waiting"><span>治理</span><strong>{{ statusLabel(finding.status) }}</strong><small>{{ finding.remediation_note ?? finding.ai_review?.remediation ?? '分配负责人并记录整改结论' }}</small></div></div><div class="risk-chain-footer"><div class="risk-chain-meta"><span>DAST 记录：{{ linked(finding).validations.length }}</span><span>SANDBOX 证据：{{ linked(finding).evidence.length }}</span></div><div class="risk-chain-actions"><button class="secondary-action" @click="scope=linked(finding).validations.length?'sandbox':'dast'">{{ linked(finding).validations.length?'进入 SANDBOX 取证':'发起 DAST 验证' }}</button></div></div></article></div></section>
    <section class="governance-two-column"><div class="panel"><div class="panel-header"><h2>跨模块攻击链</h2><span>{{ store.summary?.attack_chains?.length ?? 0 }} 条可信链路</span></div><div v-if="!store.summary?.attack_chains?.length" class="empty-project">暂未形成可信攻击链。只有风险与 DAST 或 SANDBOX 存在显式关系后才会生成。</div><div v-else class="attack-chain-list"><details v-for="chain in store.summary.attack_chains" :key="chain.id"><summary><span class="severity" :class="chain.severity">{{ severityLabel(chain.severity) }}</span><strong>{{ chain.name }}</strong><small>{{ chain.modules.join(' → ') }} · 可信度 {{ chain.confidence }}%</small></summary></details></div></div><div class="panel"><div class="panel-header"><h2>已接入模块</h2><span>{{ scopes.length-1 }} 个检测与验证模块</span></div><div class="module-result-overview"><div v-for="item in scopes.slice(1)" :key="item"><strong>{{ display[item] }}</strong><span>{{ item==='sca'?`${store.components.length} 个组件`:item==='dast'?`${store.validations.length} 条验证`:item==='sandbox'?`${store.evidence.length} 份证据`:`${store.findings.filter(i=>i.source===item.toUpperCase()).length} 条发现` }}</span></div></div></div></section>
    <section class="knowledge-preview panel"><div><BookOpen :size="22"/><div><h2>安全知识正在从项目结果中沉淀</h2><p>规则命中、误报结论、动态验证证据和修复经验会形成后续扫描可复用的项目安全上下文。</p></div></div><div class="knowledge-preview-stats"><span><strong>{{ new Set(store.findings.map(i=>i.rule_id)).size }}</strong> 条规则经验</span><span><strong>{{ store.validations.length }}</strong> 次动态验证</span><span><strong>{{ store.evidence.length }}</strong> 份运行证据</span></div></section>
    <details class="advanced-details governance-advanced-details"><summary>查看完整治理闭环、全部攻击链与项目级证据图谱</summary><div class="advanced-details-body"><pre class="json-preview">{{ JSON.stringify(store.evidenceGraph ?? {},null,2) }}</pre></div></details>
  </div>
  <ScaView v-else-if="scope==='sca'"/><SastView v-else-if="scope==='sast'"/><ModuleView v-else :module-key="scope"/>
</section></template>
