<script setup lang="ts">
import { computed, ref } from "vue"; import { ArrowRight, BookOpen } from "lucide-vue-next";
import { api, errorText } from "../api"; import { usePlatformStore } from "../stores/platform";
const store=usePlatformStore(); const report=ref<Record<string,any>|null>(null); const message=ref(""); const page=ref(1);
const rules=computed(()=>new Set(store.findings.map(i=>i.rule_id)).size); const categories=computed(()=>new Set(store.findings.map(i=>i.ai_review?.category??"未分类")).size);
const sorted=computed(()=>[...store.findings].sort((a,b)=>({critical:5,high:4,medium:3,low:2,info:1}[b.severity as string]??0)-({critical:5,high:4,medium:3,low:2,info:1}[a.severity as string]??0)));
const items=computed(()=>sorted.value.slice((page.value-1)*10,page.value*10)); const pageCount=computed(()=>Math.max(1,Math.ceil(sorted.value.length/10)));
const stages=computed(()=>[["业务上下文",store.project?.name??"未选择","仓库、源码、运行地址和负责人共同限定扫描范围"],["规则与 Skill",`${rules.value} 条规则`,`${categories.value} 类风险知识用于发现与复核`],["动态验证经验",`${store.validations.filter(i=>i.finding_id||i.component_id).length} 条`,"保存目标、请求响应、三色裁决和复现过程"],["运行时证据",`${store.evidence.filter(i=>i.finding_id||i.component_id||i.validation_id).length} 份`,"保存隔离策略、进程、文件、网络和工具调用账本"],["治理经验",`${store.findings.filter(i=>['fixed','closed','false_positive'].includes(i.status)).length} 条`,"修复结论与误报判断形成后续可复用上下文"]]);
async function generate(){if(!store.project)return;try{report.value=await api(`/aspm/projects/${store.project.id}/report`);message.value=""}catch(e){message.value=`报告生成失败：${errorText(e)}`}}
async function exportReport(format:string){if(!store.project||!report.value)return; const content=format==='html'?`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>${store.project.name} 安全报告</title><body><h1>${store.project.name} 安全报告</h1><pre>${JSON.stringify(report.value,null,2).replace(/&/g,"&amp;").replace(/</g,"&lt;")}</pre></body></html>`:JSON.stringify(report.value,null,2); const url=URL.createObjectURL(new Blob([content],{type:format==='html'?'text/html;charset=utf-8':'application/json'}));const link=document.createElement('a');link.href=url;link.download=`${store.project.name}-security-report.${format}`;link.click();URL.revokeObjectURL(url)}
const sev=(v:string)=>({critical:"严重",high:"高危",medium:"中危",low:"低危",info:"提示"}[v]??v); const status=(v:string)=>({open:"待处理",confirmed:"已确认",fixing:"整改中",retest:"待复测",fixed:"已修复",closed:"已关闭",false_positive:"误报",accepted_risk:"接受风险"}[v]??v);
</script>
<template><div v-if="!store.project" class="panel empty-project">请先选择项目，再查看该项目沉淀的安全知识。</div><section v-else class="knowledge-hub">
  <section class="knowledge-hero panel"><div><span class="section-kicker">安全知识中枢</span><h2>让检测结果变成企业可以复用的安全经验</h2><p>当前版本先把项目上下文、规则命中、动态证据、修复和误报结论组织在一起；后续再将这些经验反馈给规则和安全 Skill。</p></div><div class="knowledge-core"><BookOpen :size="30"/><strong>{{ store.project.name }}</strong><span>项目安全上下文</span></div></section>
  <section class="knowledge-flow panel"><div class="panel-header"><h2>知识如何形成</h2><span>上下文更专 → 多源发现 → 动态证明 → 知识组织</span></div><div class="knowledge-stage-grid"><template v-for="(stage,index) in stages" :key="stage[0]"><article><span>0{{ index+1 }}</span><h3>{{ stage[0] }}</h3><strong>{{ stage[1] }}</strong><p>{{ stage[2] }}</p></article><ArrowRight v-if="index<stages.length-1" :size="18"/></template></div></section>
  <section class="knowledge-metrics"><div class="metric-card"><span>规则经验</span><strong>{{ rules }}</strong></div><div class="metric-card"><span>风险分类</span><strong>{{ categories }}</strong></div><div class="metric-card"><span>动态验证</span><strong>{{ store.validations.length }}</strong></div><div class="metric-card"><span>运行证据</span><strong>{{ store.evidence.length }}</strong></div><div class="metric-card"><span>可信攻击链</span><strong>{{ store.summary?.attack_chains?.length ?? 0 }}</strong></div></section>
  <section class="panel"><div class="panel-header"><h2>当前项目知识条目</h2><span>完整结果 · 每页 10 条</span></div><table class="concise-table"><thead><tr><th>规则 / 分类</th><th>项目风险知识</th><th>验证与证据</th><th>治理结论</th></tr></thead><tbody><tr v-if="!items.length"><td colspan="4" class="empty-cell">执行检测后，规则命中和复核结论会进入这里。</td></tr><tr v-for="finding in items" :key="finding.id"><td><strong>{{ finding.rule_id }}</strong><span class="cell-subtext">{{ finding.source }} · {{ finding.ai_review?.category ?? '未分类' }}</span></td><td><span class="severity" :class="finding.severity">{{ sev(finding.severity) }}</span><strong>{{ finding.title }}</strong><span class="cell-subtext">{{ finding.ai_review?.description ?? finding.evidence ?? '暂无风险说明' }}</span></td><td>{{ store.validations.filter(i=>i.finding_id===finding.id).length || '未' }}次 DAST<span class="cell-subtext">{{ store.evidence.filter(i=>i.finding_id===finding.id).length || '无' }}份 SANDBOX 证据</span></td><td>{{ status(finding.status) }}<span class="cell-subtext">{{ finding.remediation_note ?? finding.ai_review?.remediation ?? '等待治理结论' }}</span></td></tr></tbody></table><div class="result-pagination"><span>共 {{ sorted.length }} 条，每页 10 条</span><div><button :disabled="page<=1" @click="page--">上一页</button><strong>第 {{ page }} / {{ pageCount }} 页</strong><button :disabled="page>=pageCount" @click="page++">下一页</button></div></div></section>
  <section class="panel report-delivery"><div class="panel-header"><div><span class="section-kicker">项目安全报告</span><h2>生成可交付的项目安全快照</h2></div><span>{{ report ? '报告预览已生成' : '报告不会改变现有数据' }}</span></div><p>报告汇总当前项目的已接入模块、风险、动态验证、运行时证据、可信关系、攻击链、复测结果和能力边界。先生成预览确认内容，再导出 JSON 或 HTML。</p><div class="report-actions"><button class="primary-action" @click="generate">{{ report?'刷新报告预览':'生成报告预览' }}</button><button class="secondary-action" :disabled="!report" @click="exportReport('json')">导出 JSON</button><button class="secondary-action" :disabled="!report" @click="exportReport('html')">导出 HTML</button></div><div v-if="message" class="report-error">{{ message }}</div></section>
  <section v-if="report" class="report-preview"><section class="panel"><div class="panel-header"><div><span class="section-kicker">报告预览</span><h2>{{ store.project.name }}：完整项目安全交付</h2></div><span>所有多条结果每页 10 条</span></div><pre class="json-preview">{{ JSON.stringify(report,null,2) }}</pre></section></section>
  <section class="knowledge-boundary"><strong>当前能力边界</strong><span>目前已完成知识组织和追溯视图；规则自动生成、跨项目知识推荐和基于反馈的自主演进仍属于后续能力，不会在界面中伪装成已实现。</span></section>
</section></template>
