<script setup lang="ts">
import { computed, onMounted, ref } from "vue"; import { ArrowRight } from "lucide-vue-next"; import { api, errorText } from "../api"; import { usePlatformStore } from "../stores/platform";
const props=defineProps<{moduleKey:string}>(); const store=usePlatformStore(); const selectedFinding=ref(""),selectedValidation=ref(""),strategyId=ref("web-baseline"),strategies=ref<any[]>([]),message=ref(""),page=ref(1);
const info:Record<string,[string,string]>={agent:["AGENT 智能体安全","检查 Agent、MCP、工具和插件配置风险"],dast:["DAST 动态验证","访问运行中的系统，验证风险是否能够触发"],sandbox:["SANDBOX 沙箱证据","隔离运行程序并采集进程、输出和策略证据"],aspm:["ASPM 平台治理","聚合风险、证据和整改闭环"]};
const findings=computed(()=>store.findings.filter(i=>i.source===props.moduleKey.toUpperCase())); const selected=computed(()=>store.findings.find(i=>i.id===selectedFinding.value)); const validation=computed(()=>store.validations.find(i=>i.id===selectedValidation.value)); const selectedStrategy=computed(()=>strategies.value.find(i=>i.id===strategyId.value)??strategies.value[0]);
async function load(){if(store.project&&props.moduleKey==='dast'){strategies.value=await api<any[]>(`/dast/projects/${store.project.id}/strategies${selectedFinding.value?`?finding_id=${selectedFinding.value}`:''}`).catch(()=>[]);if(strategies.value.length&&!strategies.value.some(i=>i.id===strategyId.value))strategyId.value=strategies.value[0].id}}
async function runAgent(){await store.scan("agent")}
async function runDast(){if(!store.project||!selectedFinding.value)return;try{await api("/dast/probe",{method:"POST",body:JSON.stringify({project_id:store.project.id,target_url:store.targetUrl,validator:"auto-dast",finding_id:selectedFinding.value,component_id:selected.value?.component_id??null,link_source:"explicit-selection",link_confidence:100,strategy_id:strategyId.value})});await store.refreshData();message.value="DAST 自动验证完成"}catch(e){message.value=errorText(e)}}
async function runSandbox(){if(!store.project||(!selectedFinding.value&&!selectedValidation.value))return;try{await api("/sandbox/run",{method:"POST",body:JSON.stringify({project_id:store.project.id,run_command:store.runCommand,image:store.sandboxImage,timeout_seconds:10,operator:"security-user",finding_id:selectedFinding.value||validation.value?.finding_id||null,component_id:selected.value?.component_id||validation.value?.component_id||null,validation_id:selectedValidation.value||null,link_source:"explicit-selection",link_confidence:100,strategy_name:validation.value?"DAST 结果后的隔离取证":"上游风险的隔离运行检查",purpose:"围绕已选择风险执行受控命令并保留证据",limitations:"不会主动利用漏洞；命令成功不等于漏洞成立。"})});await store.refreshData();message.value="SANDBOX 受控执行完成"}catch(e){message.value=errorText(e)}}
const severity=(v:string)=>({critical:"严重",high:"高危",medium:"中危",low:"低危",info:"提示"}[v]??v); onMounted(load);
</script>
<template><div class="governance-view module-governance-view">
  <section class="module-governance-heading"><div class="module-icon">{{ moduleKey.toUpperCase().slice(0,1) }}</div><div><h2>{{ info[moduleKey]?.[0]??moduleKey.toUpperCase() }}</h2><p>{{ info[moduleKey]?.[1]??'模块能力与数据' }}</p></div><div v-if="moduleKey==='agent'" class="module-run-actions"><span>{{ findings.length?'已完成':'尚未执行' }}</span><button class="primary-action" :disabled="store.loading" @click="runAgent">{{ store.loading?'执行中':'重新扫描并复测' }}</button></div></section>
  <section v-if="moduleKey==='agent'" class="governance-metrics"><div class="metric-card"><span>风险问题</span><strong>{{ findings.length }}</strong></div><div class="metric-card"><span>严重 / 高危</span><strong>{{ findings.filter(i=>['critical','high'].includes(i.severity)).length }}</strong></div><div class="metric-card"><span>已复核</span><strong>{{ findings.filter(i=>i.ai_review).length }}</strong></div><div class="metric-card"><span>待处理</span><strong>{{ findings.filter(i=>!['fixed','closed'].includes(i.status)).length }}</strong></div></section>
  <section v-if="moduleKey==='dast'" class="governance-metrics"><div class="metric-card"><span>验证记录</span><strong>{{ store.validations.length }}</strong></div><div class="metric-card"><span>基础风险信号</span><strong>{{ store.validations.filter(i=>i.verdict==='exploitable').length }}</strong></div><div class="metric-card"><span>需要补充验证</span><strong>{{ store.validations.filter(i=>i.verdict==='uncertain').length }}</strong></div><div class="metric-card"><span>已关联风险</span><strong>{{ store.validations.filter(i=>i.finding_id||i.component_id).length }}</strong></div></section>
  <section v-if="moduleKey==='sandbox'" class="governance-metrics"><div class="metric-card"><span>运行证据</span><strong>{{ store.evidence.length }}</strong></div><div class="metric-card"><span>执行完成</span><strong>{{ store.evidence.filter(i=>i.observed_processes?.length).length }}</strong></div><div class="metric-card"><span>进入证据链</span><strong>{{ store.evidence.filter(i=>i.finding_id||i.validation_id).length }}</strong></div><div class="metric-card"><span>隔离策略</span><strong>禁网 / 只读</strong></div></section>
  <section class="panel"><div class="panel-header"><h2>主要结果</h2><span>完整结果 · 每页 10 条</span></div>
    <section v-if="moduleKey==='dast'" class="validation-workbench"><div class="workbench-heading"><span>动态证明</span><h3>选择一条已发现风险，在运行系统中验证它是否能被触发</h3><p>只有从具体风险发起的验证才会进入证据链；当前自动能力属于 Web 基础验证，业务漏洞应补充对应测试策略。</p></div><div class="validation-form"><label><span>① 待验证风险</span><select v-model="selectedFinding" @change="load"><option value="">请选择 SAST / SCA / AGENT 风险</option><option v-for="i in store.findings" :key="i.id" :value="i.id">{{ i.source }} · {{ severity(i.severity) }} · {{ i.title }}</option></select></label><ArrowRight :size="18"/><label><span>② 验证策略</span><select v-model="strategyId" :disabled="!selectedFinding"><option v-for="i in strategies" :key="i.id" :value="i.id">{{ i.name }}</option></select></label><label><span>③ 运行目标</span><input v-model="store.targetUrl" placeholder="https://项目运行地址/具体接口"/></label><ArrowRight :size="18"/><button class="primary-action" :disabled="!selectedFinding||!store.targetUrl" @click="runDast">④ 执行验证</button></div><section v-if="selectedStrategy" class="verification-strategy-card"><div><span>本次会检查</span><strong>{{ selectedStrategy.name }}</strong><p>{{ selectedStrategy.description }}</p><ul><li v-for="i in selectedStrategy.check_items" :key="i">{{ i }}</li></ul></div><div><span>明确不检查</span><p>{{ selectedStrategy.scope_summary }}</p><ul><li v-for="i in selectedStrategy.limitations" :key="i">{{ i }}</li></ul></div></section><div v-if="selected" class="selected-risk-context"><span class="severity" :class="selected.severity">{{ severity(selected.severity) }}</span><div><strong>{{ selected.title }}</strong><small>{{ selected.source }} · {{ selected.file_path??'项目级风险' }} · {{ selected.rule_id }}</small></div><b>本次结果将回写到这条风险的证据链</b></div><div v-else class="workbench-empty">请先选择风险。没有上游风险的 URL 检查只属于 Web 基础检查，不计入漏洞证据闭环。</div></section>
    <section v-else-if="moduleKey==='sandbox'" class="validation-workbench sandbox-workbench"><div class="workbench-heading"><span>运行时取证</span><h3>围绕具体风险或 DAST 结果，在隔离环境中观察真实行为</h3><p>沙箱负责记录进程、文件、网络策略和工具调用；“命令执行成功”不等于“漏洞成立”，必须结合上游对象解释。</p></div><div class="sandbox-source-grid"><label><span>① 上游 DAST 验证（优先）</span><select v-model="selectedValidation"><option value="">不从 DAST 结果进入</option><option v-for="i in store.validations.filter(i=>i.finding_id||i.component_id)" :key="i.id" :value="i.id">{{ i.verdict }} · {{ i.target_url }}</option></select></label><label><span>或直接选择风险</span><select v-model="selectedFinding"><option value="">请选择风险</option><option v-for="i in store.findings" :key="i.id" :value="i.id">{{ i.source }} · {{ severity(i.severity) }} · {{ i.title }}</option></select></label></div><section class="verification-strategy-card sandbox-plan-card"><div><span>本次取证目的</span><strong>{{ validation?'DAST 结果后的隔离取证':'上游风险的隔离运行检查' }}</strong><p>围绕已选择风险执行受控命令并保留证据。</p></div><div><span>不能证明的事项</span><p>不会主动利用漏洞；命令成功不等于漏洞成立。</p></div></section><div class="validation-form sandbox-command-form"><label><span>② 验证命令</span><input v-model="store.runCommand"/></label><label><span>隔离镜像</span><input v-model="store.sandboxImage"/></label><button class="primary-action" :disabled="(!selectedFinding&&!selectedValidation)||!store.runCommand" @click="runSandbox">③ 执行隔离取证</button></div></section>
    <table v-if="moduleKey==='agent'" class="concise-table"><thead><tr><th>风险问题</th><th>等级</th><th>位置</th><th>处理状态</th></tr></thead><tbody><tr v-for="i in findings" :key="i.id"><td><strong>{{ i.title }}</strong><span class="cell-subtext">{{ i.ai_review?.description??i.evidence }}</span></td><td><span class="severity" :class="i.severity">{{ severity(i.severity) }}</span></td><td>{{ i.file_path??'项目级问题' }}</td><td>{{ i.status }}</td></tr></tbody></table>
    <table v-else-if="moduleKey==='dast'" class="concise-table"><thead><tr><th>关联的原始风险</th><th>验证目标 / 策略</th><th>三色裁决</th><th>验证证据</th></tr></thead><tbody><tr v-for="i in store.validations" :key="i.id"><td>{{ store.findings.find(f=>f.id===i.finding_id)?.title??'独立 Web 基础检查' }}</td><td><strong>{{ i.target_url }}</strong><span class="cell-subtext">{{ i.strategy_name??'旧记录：未保存策略' }}</span></td><td><span class="verdict-badge" :class="i.verdict">{{ i.verdict }}</span></td><td>{{ i.evidence_summary??'查看验证过程' }}</td></tr></tbody></table>
    <table v-else-if="moduleKey==='sandbox'" class="concise-table"><thead><tr><th>上游风险 / 验证</th><th>隔离执行</th><th>观察结论</th><th>运行时账本</th></tr></thead><tbody><tr v-for="i in store.evidence" :key="i.id"><td>{{ store.findings.find(f=>f.id===i.finding_id)?.title??'独立命令运行' }}</td><td><strong>{{ i.run_command }}</strong><span class="cell-subtext">{{ i.strategy_name??'隔离执行' }}</span></td><td>{{ i.evidence_summary??'未记录证据摘要' }}</td><td>文件 {{ i.observed_files?.length??0 }}；网络 {{ i.observed_network?.length??0 }}；进程 {{ i.observed_processes?.length??0 }}</td></tr></tbody></table>
    <pre v-else class="json-preview">{{ JSON.stringify(moduleKey==='aspm'?store.summary:{modules:store.modules,project:store.project},null,2) }}</pre>
  </section><section class="next-action-panel"><strong>建议动作</strong><span>{{ moduleKey==='dast'?'按策略补充业务验证，并保留关联证据。':moduleKey==='sandbox'?'结合上游风险和 DAST 裁决复核运行行为。':'复核高风险配置并进入整改闭环。' }}</span></section><p>{{ message }}</p>
</div></template>
