<script setup lang="ts">
import { computed, ref } from "vue";
import { api, errorText } from "../api";
import { usePlatformStore } from "../stores/platform";
import DataTable from "../components/DataTable.vue";
const props = defineProps<{ moduleKey: string }>(); const store = usePlatformStore(); const selectedFinding = ref(""); const selectedValidation = ref(""); const message = ref("");
const moduleInfo = computed(() => store.modules.find((item) => item.key === props.moduleKey));
const moduleFindings = computed(() => store.findings.filter((item) => String(item.source).toLowerCase() === props.moduleKey));
const findingColumns = [{ key: "title", label: "风险" }, { key: "severity", label: "级别" }, { key: "status", label: "状态" }, { key: "file_path", label: "位置" }];
async function runAgent() { await store.scan("agent"); }
async function runDast() { if (!store.project || !selectedFinding.value) { message.value = "请先选择待验证风险"; return; } try { const finding = store.findings.find(i => i.id === selectedFinding.value); await api("/dast/probe", { method: "POST", body: JSON.stringify({ project_id: store.project.id, target_url: store.targetUrl, validator: "auto-dast", finding_id: selectedFinding.value, component_id: finding?.component_id ?? null, link_source: "explicit-selection", link_confidence: 100, strategy_id: "web-baseline" }) }); await store.refreshData(); message.value = "DAST 自动验证完成"; } catch (e) { message.value = errorText(e); } }
async function runSandbox() { if (!store.project || (!selectedFinding.value && !selectedValidation.value)) { message.value = "请先选择风险或验证记录"; return; } try { const finding = store.findings.find(i => i.id === selectedFinding.value); await api("/sandbox/run", { method: "POST", body: JSON.stringify({ project_id: store.project.id, run_command: store.runCommand, image: store.sandboxImage, timeout_seconds: 10, operator: "security-user", finding_id: selectedFinding.value || null, component_id: finding?.component_id ?? null, validation_id: selectedValidation.value || null, link_source: "explicit-selection", link_confidence: 100, strategy_name: "受控动态验证", purpose: "验证关联风险", limitations: "本地隔离执行" }) }); await store.refreshData(); message.value = "SANDBOX 受控执行完成"; } catch (e) { message.value = errorText(e); } }
</script>
<template><div class="stack-layout">
  <section class="panel"><div class="panel-header"><div><h2>{{ moduleInfo?.name ?? moduleKey.toUpperCase() }}</h2><span>{{ moduleInfo?.subtitle ?? "模块能力与数据" }}</span></div><span>{{ store.enabled(moduleKey as any) ? "已启用" : "未启用" }}</span></div>
    <div v-if="moduleKey === 'agent'" class="toolbar"><label>源码路径<input v-model="store.sourcePath" /></label><button class="primary-action" :disabled="store.loading" @click="runAgent">执行 AGENT 扫描</button></div>
    <div v-else-if="moduleKey === 'dast'" class="project-form"><label>目标地址<input v-model="store.targetUrl" /></label><label>关联风险<select v-model="selectedFinding"><option value="">请选择</option><option v-for="item in store.findings" :key="item.id" :value="item.id">{{ item.source }} · {{ item.title }}</option></select></label><button class="primary-action" @click="runDast">执行动态验证</button></div>
    <div v-else-if="moduleKey === 'sandbox'" class="project-form"><label>执行命令<input v-model="store.runCommand" /></label><label>容器镜像<input v-model="store.sandboxImage" /></label><label>关联风险<select v-model="selectedFinding"><option value="">可选</option><option v-for="item in store.findings" :key="item.id" :value="item.id">{{ item.source }} · {{ item.title }}</option></select></label><label>关联验证<select v-model="selectedValidation"><option value="">可选</option><option v-for="item in store.validations" :key="item.id" :value="item.id">{{ item.verdict }} · {{ item.target_url }}</option></select></label><button class="primary-action" @click="runSandbox">执行受控沙箱</button></div>
  </section>
  <section v-if="moduleKey === 'dast'" class="panel"><div class="panel-header"><h2>验证记录</h2><span>{{ store.validations.length }} 条</span></div><DataTable :rows="store.validations" :columns="[{key:'target_url',label:'目标'},{key:'verdict',label:'裁决'},{key:'validator',label:'验证器'},{key:'created_at',label:'时间'}]" /></section>
  <section v-else-if="moduleKey === 'sandbox'" class="panel"><div class="panel-header"><h2>动态证据</h2><span>{{ store.evidence.length }} 条</span></div><DataTable :rows="store.evidence" :columns="[{key:'run_command',label:'命令'},{key:'status',label:'状态'},{key:'exit_code',label:'退出码'},{key:'created_at',label:'时间'}]" /></section>
  <section v-else-if="moduleKey === 'aspm' || moduleKey === 'tasks' || moduleKey === 'modules'" class="panel"><pre class="json-preview">{{ JSON.stringify(moduleKey === 'aspm' ? store.summary : { modules: store.modules, project: store.project }, null, 2) }}</pre></section>
  <section v-else class="panel"><div class="panel-header"><h2>模块发现</h2><span>{{ moduleFindings.length }} 条</span></div><DataTable :rows="moduleFindings" :columns="findingColumns" /></section><p>{{ message }}</p>
</div></template>
