<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { api, download, errorText } from "../api";
import { usePlatformStore } from "../stores/platform";
import DataTable from "../components/DataTable.vue";
const store = usePlatformStore(); const profile = ref<Record<string, any> | null>(null); const toolHealth = ref<Record<string, any> | null>(null); const history = ref<Record<string, any>[]>([]); const diff = ref<Record<string, any> | null>(null); const rules = ref<Record<string, any>[]>([]); const jobs = ref<Record<string, any>[]>([]); const report = ref<Record<string, any> | null>(null); const message = ref("");
const ruleDraft = reactive({ name: "", rule_id: "", severity: "medium", pattern: "", message: "", languages: ["python"] });
const findingColumns = [{ key: "title", label: "问题" }, { key: "severity", label: "级别" }, { key: "file_path", label: "文件" }, { key: "line_start", label: "行" }, { key: "status", label: "整改状态" }, { key: "remediation_owner", label: "负责人" }];
async function load() { if (!store.project) return; const id = store.project.id; [profile.value, toolHealth.value, history.value, diff.value, report.value, jobs.value] = await Promise.all([api<Record<string, any>>(`/sast/projects/${id}/profile`).catch(() => null), api<Record<string, any>>("/sast/tool-health").catch(() => null), api<Record<string, any>[]>(`/sast/projects/${id}/scan-history`).catch(() => []), api<Record<string, any>>(`/sast/projects/${id}/scan-diff`).catch(() => null), api<Record<string, any>>(`/sast/projects/${id}/report`).catch(() => null), api<Record<string, any>[]>(`/scans?project_id=${id}`).catch(() => [])]); const packs: any = await api(`/sast/projects/${id}/semgrep-rules`).catch(() => ({ semgrep_rules: [] })); rules.value = packs.semgrep_rules ?? []; }
async function saveProfile() { if (!store.project || !profile.value) return; try { profile.value = await api(`/sast/projects/${store.project.id}/profile`, { method: "PATCH", body: JSON.stringify(profile.value) }); message.value = "SAST 配置已保存"; } catch (e) { message.value = errorText(e); } }
async function validateRule() { try { const r: any = await api("/sast/rules/validate", { method: "POST", body: JSON.stringify(ruleDraft) }); message.value = r.message ?? (r.valid ? "规则有效" : "规则无效"); } catch (e) { message.value = errorText(e); } }
async function createRule() { if (!store.project) return; try { profile.value = await api(`/sast/projects/${store.project.id}/rules`, { method: "POST", body: JSON.stringify(ruleDraft) }); message.value = "规则已保存"; await load(); } catch (e) { message.value = errorText(e); } }
async function queueJob() { if (!store.project) return; try { const job = await api<Record<string, any>>("/sast/jobs", { method: "POST", body: JSON.stringify({ project_id: store.project.id, source_path: store.sourcePath, branch: store.project.default_branch }) }); jobs.value = [job, ...jobs.value]; message.value = "SAST Job 已排队。可启动本地 Worker，或点击“本次运行”由当前 API 进程执行。"; } catch (e) { message.value = `排队失败：${errorText(e)}`; } }
async function runJob(job: Record<string, any>) { try { await api(`/sast/jobs/${job.id}/run`, { method: "POST" }); message.value = "SAST Job 已完成，已生成独立扫描批次和报告。"; await load(); } catch (e) { message.value = `执行失败：${errorText(e)}`; await load(); } }
async function changeJob(job: Record<string, any>, action: "cancel" | "retry") { try { await api(`/scans/${job.id}/${action}`, { method: "POST" }); await load(); } catch (e) { message.value = `${action} 失败：${errorText(e)}`; } }
async function exportSarif() { if (!store.project) return; await download(`/sast/projects/${store.project.id}/sarif`, `${store.project.name}-sast.sarif`); }
onMounted(load);
</script>
<template><div class="stack-layout">
  <details class="advanced-details governance-advanced-details" open><summary>SAST 异步任务与可配置质量门禁</summary><div class="advanced-details-body"><section class="content-grid"><div class="panel full"><div class="panel-header"><h2>可追踪 SAST Job</h2><span>队列、进度、取消、重试和 Worker 入口</span></div><div class="filter-grid"><label class="wide-field">源码路径<input v-model="store.sourcePath" /></label><button class="primary-action" :disabled="!store.sourcePath.trim()" @click="queueJob">创建 SAST Job</button><button class="secondary-action" @click="load">刷新状态</button></div><p>常驻 Worker：<code>python scripts\sast_worker.py --max-jobs 0 --concurrency 1</code>。不启动 Worker 时，可对单个 Job 点击“本次运行”。</p><table v-if="jobs.length"><thead><tr><th>状态</th><th>阶段 / 进度</th><th>尝试</th><th>操作</th></tr></thead><tbody><tr v-for="job in jobs.filter(i=>i.scan_type==='sast_job')" :key="job.id"><td>{{ job.status }}<span class="cell-subtext">{{ job.created_at }}</span></td><td>{{ job.stage??'-' }}<span class="cell-subtext">{{ job.progress }}% {{ job.error?`· ${job.error}`:'' }}</span></td><td>{{ job.attempt }}</td><td><template v-if="job.status==='queued'"><button class="secondary-action" @click="runJob(job)">本次运行</button><button class="secondary-action" @click="changeJob(job,'cancel')">取消</button></template><button v-else-if="job.status==='failed'||job.status==='cancelled'" class="secondary-action" @click="changeJob(job,'retry')">重试</button><span v-else>-</span></td></tr></tbody></table><div v-else class="empty-project">尚无 SAST Job。</div></div><div class="panel full"><div class="panel-header"><h2>项目质量门禁</h2><span>按分支、等级、新问题和规则例外计算</span></div><div v-if="profile" class="filter-grid"><label>阻断等级<select v-model="profile.quality_gate.threshold"><option v-for="item in ['critical','high','medium','low','info','none']" :key="item">{{ item }}</option></select></label><label>分支 glob<input :value="profile.quality_gate.branch_patterns?.join(',')" @input="profile.quality_gate.branch_patterns=($event.target as HTMLInputElement).value.split(',')" /></label><label>排除规则 ID<input :value="profile.quality_gate.excluded_rule_ids?.join(',')" @input="profile.quality_gate.excluded_rule_ids=($event.target as HTMLInputElement).value.split(',')" /></label><label class="inline-check"><input v-model="profile.quality_gate.enabled" type="checkbox"/>启用门禁</label><label class="inline-check"><input v-model="profile.quality_gate.block_new_only" type="checkbox"/>只阻断新增问题</label><button class="secondary-action" @click="saveProfile">保存门禁</button></div><div v-if="message" class="empty-project">{{ message }}</div></div></section></div></details>
  <details class="advanced-details governance-advanced-details" open><summary>SAST 语义分析、Git 基线与交付门禁</summary><div class="advanced-details-body"><section class="content-grid"><div class="panel full"><div class="panel-header"><h2>受限语义分析</h2><span>Python AST + 直接本地跨函数数据流；JS/TS 为保守本地数据流</span></div><p>覆盖 SQL、命令执行、SSRF、路径穿越和不安全反序列化的 Source → Sink → Sanitizer 检查。结果是可复核的静态线索，不等同于全程序可达性或可利用性证明。</p><div v-if="profile" class="filter-grid"><label>Git 基线 revision<input v-model="profile.git_baseline_ref" placeholder="例如 origin/main 或 HEAD~1"/></label><label class="inline-check"><input v-model="profile.scan_git_history_secrets" type="checkbox"/>扫描 Git 历史中的密钥标识（仅保存路径）</label><label class="inline-check"><input v-model="profile.changed_files_only" type="checkbox"/>仅扫描基线差异文件</label><button class="secondary-action" @click="saveProfile">保存基线配置</button></div></div><div class="panel"><div class="panel-header"><h2>质量门禁</h2><span>{{ report?.quality_gate?.status??'等待扫描' }}</span></div><div class="kv-list"><div><span>阈值</span><strong>{{ report?.quality_gate?.threshold??'high' }}</strong></div><div><span>阻断 Finding</span><strong>{{ report?.quality_gate?.blocking_finding_count??0 }}</strong></div><div><span>本次扫描</span><strong>{{ report?.summary?.finding_count??0 }}</strong></div></div></div><div class="panel"><div class="panel-header"><h2>Git 证据</h2><span>{{ report?.git?.available?'已关联':'等待 Git 项目扫描' }}</span></div><div class="kv-list"><div><span>基线</span><strong>{{ report?.git?.baseline_ref??'未设置' }}</strong></div><div><span>差异文件</span><strong>{{ report?.git?.changed_files?.length??0 }}</strong></div><div><span>历史密钥路径</span><strong>{{ report?.git?.history_secret_count??0 }}</strong></div></div></div></section></div></details>
  <section class="metric-grid"><article class="metric-card"><span>SAST 发现</span><strong>{{ store.findings.filter(i => i.source === 'SAST').length }}</strong></article><article class="metric-card"><span>严重 / 高危</span><strong>{{ store.findings.filter(i => i.source === 'SAST' && ['critical','high'].includes(String(i.severity).toLowerCase())).length }}</strong></article><article class="metric-card"><span>扫描批次</span><strong>{{ history.length }}</strong></article><article class="metric-card"><span>规则包</span><strong>{{ rules.length }}</strong></article></section>
  <section class="panel"><div class="panel-header"><h2>SAST 扫描</h2><span>{{ toolHealth?.status ?? toolHealth?.overall_status ?? "工具状态未检查" }}</span></div><div class="toolbar"><label>源码路径<input v-model="store.sourcePath" /></label><button class="primary-action" :disabled="store.loading" @click="store.scan('sast').then(load)">开始扫描并复测</button><button class="secondary-action" @click="store.runSastReview">Sub-agent 复核</button><button class="secondary-action" @click="exportSarif">导出 SARIF</button></div></section>
  <section class="panel"><div class="panel-header"><h2>静态审计发现</h2><span>支持整改闭环</span></div><DataTable :rows="store.findings.filter(i => i.source === 'SAST')" :columns="findingColumns" /></section>
  <details class="panel" open><summary>SAST 项目配置、门禁与 Git 基线</summary><div v-if="profile" class="project-form"><label>Git 基线<input v-model="profile.git_baseline_ref" /></label><label>质量门禁 JSON<textarea v-model="profile.quality_gate_text" :placeholder="JSON.stringify(profile.quality_gate ?? {}, null, 2)" /></label><label class="check-control"><input v-model="profile.scan_git_history_secrets" type="checkbox" />扫描 Git 历史密钥</label><label class="check-control"><input v-model="profile.changed_files_only" type="checkbox" />仅扫描变更文件</label><button class="primary-action" @click="saveProfile">保存项目配置</button></div></details>
  <details class="panel"><summary>自定义规则与 Semgrep 规则包</summary><div class="project-form"><label>规则名称<input v-model="ruleDraft.name" /></label><label>规则 ID<input v-model="ruleDraft.rule_id" /></label><label>严重性<select v-model="ruleDraft.severity"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>匹配表达式<textarea v-model="ruleDraft.pattern" /></label><label>提示信息<input v-model="ruleDraft.message" /></label><div class="toolbar"><button class="secondary-action" @click="validateRule">校验规则</button><button class="primary-action" @click="createRule">保存规则</button></div></div><DataTable :rows="rules" :columns="[{key:'name',label:'规则包'},{key:'enabled',label:'启用'},{key:'status',label:'状态'},{key:'version',label:'版本'}]" /></details>
  <details class="panel"><summary>扫描历史、复测差异与报告</summary><div class="split-grid"><pre class="json-preview">{{ JSON.stringify(history, null, 2) }}</pre><pre class="json-preview">{{ JSON.stringify(diff ?? report ?? {}, null, 2) }}</pre></div></details><p class="helper-text">{{ message }}</p>
</div></template>
