<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { api, download, errorText } from "../api";
import { usePlatformStore } from "../stores/platform";
import DataTable from "../components/DataTable.vue";
const store = usePlatformStore(); const profile = ref<Record<string, any> | null>(null); const toolHealth = ref<Record<string, any> | null>(null); const history = ref<Record<string, any>[]>([]); const diff = ref<Record<string, any> | null>(null); const rules = ref<Record<string, any>[]>([]); const jobs = ref<Record<string, any>[]>([]); const report = ref<Record<string, any> | null>(null); const message = ref("");
const ruleDraft = reactive({ name: "", rule_id: "", severity: "medium", pattern: "", message: "", languages: ["python"] });
const findingColumns = [{ key: "title", label: "问题" }, { key: "severity", label: "级别" }, { key: "file_path", label: "文件" }, { key: "line_start", label: "行" }, { key: "status", label: "整改状态" }, { key: "remediation_owner", label: "负责人" }];
async function load() { if (!store.project) return; const id = store.project.id; [profile.value, toolHealth.value, history.value, diff.value, report.value, jobs.value] = await Promise.all([api<Record<string, any>>(`/sast/projects/${id}/profile`).catch(() => null), api<Record<string, any>>("/sast/tool-health").catch(() => null), api<Record<string, any>[]>(`/sast/projects/${id}/scan-history`).catch(() => []), api<Record<string, any>>(`/sast/projects/${id}/scan-diff`).catch(() => null), api<Record<string, any>>(`/sast/projects/${id}/report`).catch(() => null), api<Record<string, any>[]>(`/scans?project_id=${id}`).catch(() => [])]); const packs: any = await api(`/sast/projects/${id}/semgrep-rules`).catch(() => ({ semgrep_rules: [] })); rules.value = packs.semgrep_rules ?? []; }
async function saveProfile() { if (!store.project || !profile.value) return; try { profile.value = await api(`/sast/projects/${store.project.id}/profile`, { method: "PATCH", body: JSON.stringify(profile.value) }); message.value = "SAST 配置已保存"; } catch (e) { message.value = errorText(e); } }
async function validateRule() { try { const r: any = await api("/sast/rules/validate", { method: "POST", body: JSON.stringify(ruleDraft) }); message.value = r.message ?? (r.valid ? "规则有效" : "规则无效"); } catch (e) { message.value = errorText(e); } }
async function createRule() { if (!store.project) return; try { profile.value = await api(`/sast/projects/${store.project.id}/rules`, { method: "POST", body: JSON.stringify(ruleDraft) }); message.value = "规则已保存"; await load(); } catch (e) { message.value = errorText(e); } }
async function exportSarif() { if (!store.project) return; await download(`/sast/projects/${store.project.id}/sarif`, `${store.project.name}-sast.sarif`); }
onMounted(load);
</script>
<template><div class="stack-layout">
  <section class="metric-grid"><article class="metric-card"><span>SAST 发现</span><strong>{{ store.findings.filter(i => i.source === 'SAST').length }}</strong></article><article class="metric-card"><span>严重 / 高危</span><strong>{{ store.findings.filter(i => i.source === 'SAST' && ['critical','high'].includes(String(i.severity).toLowerCase())).length }}</strong></article><article class="metric-card"><span>扫描批次</span><strong>{{ history.length }}</strong></article><article class="metric-card"><span>规则包</span><strong>{{ rules.length }}</strong></article></section>
  <section class="panel"><div class="panel-header"><h2>SAST 扫描</h2><span>{{ toolHealth?.status ?? toolHealth?.overall_status ?? "工具状态未检查" }}</span></div><div class="toolbar"><label>源码路径<input v-model="store.sourcePath" /></label><button class="primary-action" :disabled="store.loading" @click="store.scan('sast').then(load)">开始扫描并复测</button><button class="secondary-action" @click="store.runSastReview">Sub-agent 复核</button><button class="secondary-action" @click="exportSarif">导出 SARIF</button></div></section>
  <section class="panel"><div class="panel-header"><h2>静态审计发现</h2><span>支持整改闭环</span></div><DataTable :rows="store.findings.filter(i => i.source === 'SAST')" :columns="findingColumns" /></section>
  <details class="panel" open><summary>SAST 项目配置、门禁与 Git 基线</summary><div v-if="profile" class="project-form"><label>Git 基线<input v-model="profile.git_baseline_ref" /></label><label>质量门禁 JSON<textarea v-model="profile.quality_gate_text" :placeholder="JSON.stringify(profile.quality_gate ?? {}, null, 2)" /></label><label class="check-control"><input v-model="profile.scan_git_history_secrets" type="checkbox" />扫描 Git 历史密钥</label><label class="check-control"><input v-model="profile.changed_files_only" type="checkbox" />仅扫描变更文件</label><button class="primary-action" @click="saveProfile">保存项目配置</button></div></details>
  <details class="panel"><summary>自定义规则与 Semgrep 规则包</summary><div class="project-form"><label>规则名称<input v-model="ruleDraft.name" /></label><label>规则 ID<input v-model="ruleDraft.rule_id" /></label><label>严重性<select v-model="ruleDraft.severity"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>匹配表达式<textarea v-model="ruleDraft.pattern" /></label><label>提示信息<input v-model="ruleDraft.message" /></label><div class="toolbar"><button class="secondary-action" @click="validateRule">校验规则</button><button class="primary-action" @click="createRule">保存规则</button></div></div><DataTable :rows="rules" :columns="[{key:'name',label:'规则包'},{key:'enabled',label:'启用'},{key:'status',label:'状态'},{key:'version',label:'版本'}]" /></details>
  <details class="panel"><summary>扫描历史、复测差异与报告</summary><div class="split-grid"><pre class="json-preview">{{ JSON.stringify(history, null, 2) }}</pre><pre class="json-preview">{{ JSON.stringify(diff ?? report ?? {}, null, 2) }}</pre></div></details><p class="helper-text">{{ message }}</p>
</div></template>
