<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { api, errorText } from "../api";
import { usePlatformStore } from "../stores/platform";
import DataTable from "../components/DataTable.vue";
import { formatBeijing } from "../utils";
const store = usePlatformStore();
const toolHealth = ref<Record<string, any> | null>(null); const policies = ref<Record<string, any> | null>(null); const exceptions = ref<Record<string, any>[]>([]); const vex = ref<Record<string, any>[]>([]); const intelligence = ref<Record<string, any> | null>(null); const message = ref("");
const exceptionDraft = reactive({ component_id: "", reason: "", requester: "", requester_role: "developer", expires_at: "" });
const vexDraft = reactive({ component_id: "", vulnerability_id: "", status: "not_affected", justification: "", actor: "" });
const importDraft = reactive({ kind: "intelligence", source: "manual-import", entries: "" });
const componentColumns = [{ key: "name", label: "组件" }, { key: "version", label: "版本" }, { key: "ecosystem", label: "生态" }, { key: "dependency_type", label: "依赖关系" }, { key: "risk_status", label: "风险" }, { key: "vulnerabilities", label: "漏洞", format: (v: any) => String(Array.isArray(v) ? v.length : v ?? 0) }, { key: "license", label: "许可证" }];
const historyColumns = [{ key: "scan_task_id", label: "批次", format: (v: any) => String(v ?? "").slice(0, 8) }, { key: "status", label: "状态" }, { key: "created_at", label: "开始时间", format: formatBeijing }, { key: "component_count", label: "组件" }, { key: "vulnerability_count", label: "漏洞" }, { key: "tool_status", label: "增强引擎", format: (_: any, row: any) => row.tool_status?.status ?? row.enhanced_status ?? "未启用" }];
const current = computed(() => store.scaHistory.find((item) => item.scan_task_id === store.scaScanId));
async function loadAdvanced() { if (!store.project) return; const id = store.project.id; try { [toolHealth.value, policies.value, exceptions.value, vex.value, intelligence.value] = await Promise.all([api<Record<string, any>>("/sca/tool-health").catch(() => null), api<Record<string, any>>("/sca/policies").catch(() => null), api<Record<string, any>[]>(`/sca/projects/${id}/exceptions`).catch(() => []), api<Record<string, any>[]>(`/sca/projects/${id}/vex`).catch(() => []), api<Record<string, any>>("/sca/intelligence/status").catch(() => null)]); } catch (e) { message.value = errorText(e); } }
async function addException() { if (!store.project) return; const component = store.components.find(i => i.id === exceptionDraft.component_id); if (!component || !exceptionDraft.reason.trim()) return; try { await api(`/sca/projects/${store.project.id}/exceptions`, { method: "POST", body: JSON.stringify({ ecosystem: component.ecosystem, package_name: component.name, package_version: component.version, exception_type: "risk_acceptance", reason: exceptionDraft.reason, requester: exceptionDraft.requester || null, requester_role: exceptionDraft.requester_role, expires_at: exceptionDraft.expires_at || null }) }); Object.assign(exceptionDraft, { component_id: "", reason: "", requester: "", requester_role: "developer", expires_at: "" }); await loadAdvanced(); message.value = "例外申请已提交"; } catch (e) { message.value = errorText(e); } }
async function decideException(id: string, status: string) { try { await api(`/sca/exceptions/${id}`, { method: "PATCH", body: JSON.stringify({ status, approver: "platform-admin", approver_role: "security" }) }); await loadAdvanced(); } catch (e) { message.value = errorText(e); } }
async function addVex() { if (!store.project) return; const component = store.components.find(i => i.id === vexDraft.component_id); if (!component || !vexDraft.vulnerability_id.trim()) return; try { await api(`/sca/projects/${store.project.id}/vex`, { method: "POST", body: JSON.stringify({ ecosystem: component.ecosystem, package_name: component.name, package_version: component.version, vulnerability_id: vexDraft.vulnerability_id, status: vexDraft.status, justification: vexDraft.justification || null, actor: vexDraft.actor || null }) }); await loadAdvanced(); message.value = "VEX 结论已保存"; } catch (e) { message.value = errorText(e); } }
async function importEntries() { try { const entries = JSON.parse(importDraft.entries); if (!Array.isArray(entries)) throw new Error("请输入 JSON 数组"); const path = importDraft.kind === "osv" ? "/sca/osv-mirror/import" : "/sca/intelligence/import"; await api(path, { method: "POST", body: JSON.stringify({ entries, source: importDraft.source || "manual-import" }) }); importDraft.entries = ""; await loadAdvanced(); message.value = "离线数据已导入"; } catch (e) { message.value = errorText(e); } }
onMounted(loadAdvanced);
</script>
<template><div class="stack-layout">
  <section class="metric-grid"><article class="metric-card"><span>当前快照组件</span><strong>{{ store.counts.components }}</strong></article><article class="metric-card"><span>风险组件</span><strong>{{ store.counts.riskComponents }}</strong></article><article class="metric-card"><span>严重 / 高危发现</span><strong>{{ store.counts.severe }}</strong></article><article class="metric-card"><span>当前批次</span><strong>{{ store.scaScanId?.slice(0, 8) ?? "-" }}</strong></article></section>
  <section class="panel"><div class="panel-header"><div><h2>SCA 扫描与 SBOM</h2><span>组件数按当前扫描快照统计；复测对比的问题数单独展示</span></div></div><div class="toolbar"><label class="check-control"><input v-model="store.scaEnhanced" type="checkbox" /> 默认启用 Syft/Grype 增强扫描</label><button class="primary-action" :disabled="!store.project || store.loading" @click="store.scan('sca')">重新扫描并复测</button><button class="secondary-action" @click="store.exportSbom('cyclonedx')">导出 CycloneDX</button><button class="secondary-action" @click="store.exportSbom('spdx')">导出 SPDX</button><button class="secondary-action" @click="store.exportScaReport">导出 SCA 报告</button></div><p v-if="current" class="helper-text">当前快照：{{ current.scan_task_id }} · {{ current.created_at }} · 增强引擎 {{ current.tool_status?.status ?? current.enhanced_status ?? "未启用" }}</p></section>
  <section class="panel"><div class="panel-header"><h2>扫描历史</h2><span>点击批次切换快照</span></div><DataTable :rows="store.scaHistory" :columns="historyColumns" /><div class="chip-list"><button v-for="item in store.scaHistory" :key="item.scan_task_id" class="filter-chip" :class="{ active: item.scan_task_id === store.scaScanId }" @click="store.selectScaSnapshot(item.scan_task_id)">{{ item.scan_task_id.slice(0, 8) }}</button></div></section>
  <section class="panel"><div class="panel-header"><h2>当前快照组件清单</h2><span>{{ store.components.length }} 个组件</span></div><DataTable :rows="store.components" :columns="componentColumns" /></section>
  <section class="panel"><div class="panel-header"><h2>最近一次复测对比</h2><span>比较的是风险问题，不是组件总数</span></div><div class="metric-grid"><article class="metric-card"><span>仍然存在的问题</span><strong>{{ store.retests.sca?.still_open_count ?? store.retests.sca?.still_exists ?? 0 }}</strong></article><article class="metric-card"><span>已经消失</span><strong>{{ store.retests.sca?.resolved_count ?? store.retests.sca?.resolved ?? 0 }}</strong></article><article class="metric-card"><span>新增问题</span><strong>{{ store.retests.sca?.new_count ?? store.retests.sca?.new ?? 0 }}</strong></article><article class="metric-card"><span>发生变化</span><strong>{{ store.retests.sca?.changed_count ?? store.retests.sca?.changed ?? 0 }}</strong></article></div></section>
  <details class="panel" open><summary>SCA 高级治理与离线能力</summary><div class="metric-grid"><article class="metric-card"><span>Syft/Grype 工具链</span><strong>{{ toolHealth?.status ?? toolHealth?.overall_status ?? "未检查" }}</strong></article><article class="metric-card"><span>策略规则</span><strong>{{ policies?.vulnerability_rules?.length ?? policies?.rule_count ?? 0 }}</strong></article><article class="metric-card"><span>风险例外</span><strong>{{ exceptions.length }}</strong></article><article class="metric-card"><span>VEX 声明</span><strong>{{ vex.length }}</strong></article></div><div class="split-grid"><div><h3>依赖图谱</h3><pre class="json-preview">{{ JSON.stringify(store.dependencyGraph ?? {}, null, 2) }}</pre></div><div><h3>离线情报状态</h3><pre class="json-preview">{{ JSON.stringify(intelligence ?? {}, null, 2) }}</pre></div></div>
    <details><summary>风险例外审批</summary><div class="project-form"><label>风险组件<select v-model="exceptionDraft.component_id"><option value="">请选择</option><option v-for="item in store.components.filter(i => i.risk_status !== 'clean')" :key="item.id" :value="item.id">{{ item.name }} {{ item.version }}</option></select></label><label>业务理由<input v-model="exceptionDraft.reason" /></label><label>申请人<input v-model="exceptionDraft.requester" /></label><label>失效日期<input v-model="exceptionDraft.expires_at" type="date" /></label><button class="primary-action" @click="addException">提交申请</button></div><div v-for="item in exceptions" :key="item.id" class="project-row"><div><strong>{{ item.package_name }} · {{ item.status }}</strong><span>{{ item.reason }}</span></div><div class="toolbar"><button v-if="item.status === 'pending'" class="secondary-action" @click="decideException(item.id, 'approved')">批准</button><button v-if="item.status === 'pending'" class="secondary-action" @click="decideException(item.id, 'rejected')">拒绝</button><button v-if="item.status === 'approved'" class="secondary-action" @click="decideException(item.id, 'revoked')">撤销</button></div></div></details>
    <details><summary>VEX 适用性结论</summary><div class="project-form"><label>组件<select v-model="vexDraft.component_id" @change="vexDraft.vulnerability_id = store.components.find(i => i.id === vexDraft.component_id)?.vulnerability_ids?.[0] ?? ''"><option value="">请选择</option><option v-for="item in store.components.filter(i => i.vulnerability_ids?.length)" :key="item.id" :value="item.id">{{ item.name }} · {{ item.vulnerability_ids.join(', ') }}</option></select></label><label>漏洞 ID<input v-model="vexDraft.vulnerability_id" /></label><label>结论<select v-model="vexDraft.status"><option value="not_affected">未受影响</option><option value="fixed">已修复</option><option value="affected">受影响</option><option value="under_investigation">调查中</option></select></label><label>依据<textarea v-model="vexDraft.justification" /></label><button class="primary-action" @click="addVex">保存 VEX</button></div><pre class="json-preview">{{ JSON.stringify(vex, null, 2) }}</pre></details>
    <details><summary>导入离线 OSV / CVSS / EPSS / KEV 数据</summary><div class="project-form"><label>数据类型<select v-model="importDraft.kind"><option value="intelligence">CVSS / EPSS / KEV</option><option value="osv">OSV 镜像</option></select></label><label>来源<input v-model="importDraft.source" /></label><label>JSON 数组<textarea v-model="importDraft.entries" /></label><button class="primary-action" @click="importEntries">导入数据</button></div></details>
    <details><summary>当前策略快照</summary><pre class="json-preview">{{ JSON.stringify(policies ?? {}, null, 2) }}</pre></details><button class="secondary-action" @click="loadAdvanced">刷新高级状态</button><p>{{ message }}</p></details>
</div></template>
